using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// this interface will be used in other elements, not just the direct inherited classes of UIElement
public interface IUIStyle
{
    // data contains info for colors and element sprites, but we want those in two different functions. no need to set them all the time
    public void SetColors(UIStyleData style);
    public void SetStyle(UIStyleData style);
}

// using an abstract class so our inhereted classes know they must implement certain functions
// this class is only implemented by elements that are generated by the UIDrawer
// IMPORTANT NOTE: all fields must be public or exposed to the inspector in some way for them to be saved from the LayoutGenerator->this.SetInfo()
public abstract class UIElement : MonoBehaviour, IUIStyle
{
    public string Name { get { return elementName; } }
    protected string elementName = string.Empty;
    public abstract void SetInfo(UIElementData data, LayoutAlignment alignment, ScreenSide screenSide);
    public abstract void SetColors(UIStyleData style);
    public abstract void SetStyle(UIStyleData style);
}
